server:
  port: 10000

spring:
  application:
    name: user-service
    index: 7
  data:
    mongodb:
      host: localhost
      port: 27017
      database: restaurant

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
